### ISSUE TITLE
Default ranked players unable to combine and put enchants on items

### ISSUE THREAD

**Issue by Jarred2311** [Loikas/ExpandedEnchants#16]
Default players on the server with no permission are unable to combine books and tools with enchantments, I tried every permission listed but none of them have a permission to combine and enchant. When they try to do it nothing shows up this goes for vanilla enchants above max level swell please let me know.

**Comment by Loikas** [comment]
What are they trying to combine? Are you able to combine the things they can't?

**Comment by Jarred2311** [comment]
Yes I can do everything as an op but any default member cannot combine things together, like anything at all, they are all playing on Xbox if that’s a issue

**Comment by Loikas** [comment]
It shouldn't be.
Are you using any other plugins? 
Are they able to put things in the anvil?
Are they able to combine vanilla enchantments with tools and or other enchantments?

The combining of things in an anvil isn't based on any permission in my plugin. So a default user should be able to do everything an op can do

**Comment by Jarred2311** [comment]
We have a bunch of other enchants maybe the other enchanting plug-in is what’s messing it up? 
They can put things in the anvil and combine vanilla enchants as long as they don’t exceed vanilla max levels

**Comment by Loikas** [comment]
Are they able to apply my custom enchants to items?
Do you get any errors in the console?

**Comment by Jarred2311** [comment]
No the custom enchants don’t work, although they work for me as op. No errors in the console just nothing shows up in the anvil when the default player puts a armour peice and custom enchant book in

**Comment by Loikas** [comment]
Can you try removing your other plugins?
Or if you cant maybe create a small server to test if it is the same on that server

**Comment by Jarred2311** [comment]
Sure is there any plugins you know of that are forsure not compatible  with yours

**Comment by Loikas** [comment]
There were issues earlier with an older version of Deadly Disasters and some magic plugin

**Comment by Jarred2311** [comment]
I see, it didn’t seem to work can you create a permission to allow default users to use it? Or whoever has the permission to use the anvil to combine them

**Comment by Loikas** [comment]
So the only plugin you had was ExpandedEnchants and still you were the only one able to combine items from the plugin?

**Comment by Jarred2311** [comment]
Well no, I wasn’t able to remove all of them as it would’ve been a huge headache to apply them all again.

**Comment by Loikas** [comment]
Ah oke, yeah i understand. 
Are you hosting the server yourself? Or are you hosting it using a website

**Comment by Jarred2311** [comment]
Hosting through a website

**Comment by Loikas** [comment]
Would you be oke with joining my server for a moment to see if you are unable to enchant items?

**Comment by Jarred2311** [comment]
Sure yes.

**Comment by Loikas** [comment]
Here is the ip: play.muntinga.info:25566

**Comment by Jarred2311** [comment]
![Uploading Screen Shot 2022-03-30 at 2.53.15 PM.png…]()

**Comment by Loikas** [comment]
Problem with GeyserMC or Floodgate
