### ISSUE TITLE
Direct will delete items if your inventory is full

### ISSUE THREAD

**Issue by NebbyOtt** [Loikas/ExpandedEnchants#19]
Is there a way to make it drop when it would otherwise be snapped?
Also is there just a spot suggestions? We're really enjoying this plugin and I a couple ideas that aren't exactly issues.

**Comment by Loikas** [comment]
Oh its fine if you put suggestions here, otherwise you could put them in the discussion tab on spigot.
Hm thats weird because I thought I already fixed that
I'll look into it

**Comment by Loikas** [comment]
This is also solved for me

**Comment by NebbyOtt** [comment]
H

**Comment by NebbyOtt** [comment]
Like you fixed the issue or like you don't have the issue?

**Comment by Loikas** [comment]
I don't have the issue

**Comment by NebbyOtt** [comment]
So I was just typing out how I just tested it in my server's creative world and it was actually working, and I felt so silly and I must have just been going so fast that I didn't see things on the floor but, no, my inventory was full and there wasn't a SINGLE piece of Deepslate on the ground, I just went back to the survival world and tested with my survival pick and sure enough, Things arn't dropping!
Here is what the pick looks like
![image](https://user-images.githubusercontent.com/102494520/169691095-da5e647a-e7ab-4831-a5bc-67efc0b9a2ff.png)
My buffs (premium potion from the server's store)
![image](https://user-images.githubusercontent.com/102494520/169691101-53c960fb-3f9a-4d82-b16f-271d9d48bcfc.png)

**Comment by Loikas** [comment]
Oh yes I see, its when you use autosmelt and direct together
I'll fix it right away
