### ISSUE TITLE
Enchanted Book recipe doesn't work, and /ee reload does not reload custom recipes

### ISSUE THREAD

**Issue by NebbyOtt** [Loikas/ExpandedEnchants#20]
I'm sorry to hit you with so many issues. I'm not sure if all crafting table recipes are broken by something and recipes not refreshing is just a consequence of that, but I can't test that because I can't get my hands on an empty enchanting book

**Comment by Loikas** [comment]
Are there any errors in you console? Which mc version are you using? What happens if you put in the items for the custom book? 
/ee reload only reloads the config
You have to reload the whole server if you want to reload custom recipes

Its good that you report the issues! Gives me something to do :)

**Comment by Loikas** [comment]
Also to try the other recipes you can give yourself a level 1 book and use that to create level 2 to see if the recipe works

**Comment by NebbyOtt** [comment]
There are no errors in the console except for the new issue, Version is 1.18.1, If I put the items for the custom book into the crafting table in the same configuration, including air, absolutely nothing happens, like it's an invalid recipe. And I am able to combine two custom enchantments to increase their level in an anvil.

And thank you for being so sweet! I was actually telling people about how sweet you are in my stream, I had a lot of suggestions when I was looking around town for a decent enchantment plugin for my smp, but this is the only one that really spoke to me. This one feels fun and interesting, I love every part of it. Thanks for being such an awesome person :)

**Comment by Loikas** [comment]
Can you send the error? What do you put in the recipe in the place of the empty book?
Thankyou thats really nice to hear!

**Comment by NebbyOtt** [comment]
I'm afraid there is no error in the console except for the version warning, and i just place a normal minecraft 'Book' item in the center of the crafting table and an Emerald above it, i triple and quadruple checked that that is exactly what the recipe says to do

**Comment by NebbyOtt** [comment]
Are you able to recreate this issue? Would you like a list of plugins?

**Comment by Loikas** [comment]
Im gonna try now, what if you try to craft for examplehealth boost 2 using health boost 1

**Comment by Loikas** [comment]
Its possible for me to craft an empty book. 
Thats weird

**Comment by Loikas** [comment]
Is the recipe in the recipes menu? And are you sure that you have version 1.6.1? Because the direct issue is already solved for me

**Comment by Loikas** [comment]
Did you create a recipes.yml file?

**Comment by NebbyOtt** [comment]
I did create a recipes.yml file, because the Oresite recipe is kind of unreasonable being stone diamond ore, that stuff is EXTREMELY rare in 1.18, so I made a custom recipe to change that to deepslate diamond ore. That actually ties in to one of my suggestions, I really want to see a true/false config option to allow Oresite to show you all ores from previous levels. So level 2 would show you Coal Iron and Copper, instead of just Iron and Copper. I would enable this given how extremely expensive the final levels of the enchantment can be, and if the helmet ever breaks or you lose it? Yikes. I always feel like a large price is balance enough for an op mechanic anyway. So I would like a config option to allow that functionality.

**Comment by Loikas** [comment]
Can I see what you put in the recipes.yml file?
Thats a good suggestion, i'll add that aswell

**Comment by NebbyOtt** [comment]
```
ee_recipe_oresight:
    Ingredients:
        A: AIR
        B: NETHERITE_SCRAP
        C: AIR
        D: IRON_BLOCK
        E: ENCHANTED_BOOK
        F: DEEPSLATE_DIAMOND_ORE
        G: AIR
        H: LAPIS_LAZULI
    Amounts:
        - 0
        - 1
        - 0
        - 10
        - 1
        - 10
        - 0
        - 16
        - 0
    Advanced:
        Enchantment:
        Level:
```
I remember I was having issues getting the custom recipe to work so I added the advanced thing hoping it would help, then I did other things and it worked.

Also thank you!

**Comment by Loikas** [comment]
Are you able to craft stuff if ExpandedEnchants is the only plugin?

**Comment by NebbyOtt** [comment]
Well I copied the jar and config to an older version of my server still on my computer and tried to craft a book, yeeah, the book thing worked... that tells me that another plugin is doing some bad things and I strongly believe it's Oraxen, idk how, because it shouldn't be effecting things especially things pulled directly pulled out of the creative menu, but it is a plugin that deals with creating custom items and it did break tripwire blocks.

**Comment by Loikas** [comment]
I'll test it

**Comment by NebbyOtt** [comment]
Here's everything I have in my public server
![image](https://user-images.githubusercontent.com/102494520/169692555-139ab79d-e8e9-412e-9ad4-0054d6bc6f9e.png)

And here's everything you can cross off of that list
![image](https://user-images.githubusercontent.com/102494520/169692585-3ad6b046-50b9-4992-8252-a37f410f3296.png)

**Comment by Loikas** [comment]
What is the oraxon reset recipes set to in you oraxon settings?

**Comment by NebbyOtt** [comment]
true, should I change to false and restart?

**Comment by Loikas** [comment]
Yeah see if that helps

**Comment by NebbyOtt** [comment]
![image](https://user-images.githubusercontent.com/102494520/169692836-69a71e29-5eac-41f6-b2b3-17567279cdfd.png)

**Comment by Loikas** [comment]
I assume it works now?

**Comment by Loikas** [comment]
I hope that doesnt break anything in oraxon then

**Comment by NebbyOtt** [comment]
Yep, it was Oraxen, not the first problem that damn plugin has given me either

**Comment by NebbyOtt** [comment]
According to the comment within its just for quickly testing new recipies and whatnot, not something vital for function

**Comment by NebbyOtt** [comment]
Just for the sake of organization I'm gonna shift that suggestion to a new thread and then head to bed, thanks for all your help!! Your a real sweet person <3

**Comment by Loikas** [comment]
Happy that we fixed it! 
Which suggestion?

**Comment by NebbyOtt** [comment]
Lol you saw, I just went and did it before I saw you respond. :p
