### ISSUE TITLE
Mod thinks it's out of date

### ISSUE THREAD

**Issue by NebbyOtt** [Loikas/ExpandedEnchants#21]
In another thread you told me to check the console for any errors, well I found one that warned that EE is out of date, that I have 1.6, and the latest version is 1.6.1, which is funny because I could have SWOORN I was on 1.6.1, I felt so silly so I updated and restarted and retried the Enchanted Book recipe, still didn't work, I go back to the console and it gave me the same warning. And now that the ingame chat is new I can see it posted that there too.

**Comment by Loikas** [comment]
Yeah thats an oopsie on my side because version 1.6.1 thinks its version 1.6 so it will keep telling you to update

**Comment by Loikas** [comment]
Fixed in 1.6.2
