### ISSUE TITLE
[Suggestion] New config option for Oresight

### ISSUE THREAD

**Issue by NebbyOtt** [Loikas/ExpandedEnchants#22]
I really want to see a true/false config option to allow Oresight to show you all ores from previous levels. So level 2 would show you Coal Iron and Copper, instead of just Iron and Copper. I would enable this given how extremely expensive the final levels of the enchantment can be, and if the helmet ever breaks or you lose it? Yikes. I always feel like a large price is balance enough for an op mechanic anyway. So I would like a config option to allow that functionality.

**Comment by Loikas** [comment]
Added in version 1.6.2
