### ISSUE TITLE
1.6.2, Issues with new Autosmelt and Direct mechanics

### ISSUE THREAD

**Issue by NebbyOtt** [Loikas/ExpandedEnchants#23]
Autosmelting stone gives xp (lol) I feel like this should be restricted to ores and wood

Mining granite andesite and diorite with Direct drop physically when there is space in the inventory, this only happens when Direct AND Autosmelt are together on a pick

**Comment by Loikas** [comment]
Well smelting stone in a furnace also gives a bit of xp,
But i cant set the xp amount to a decimal value

Thats weird i'll take a look

**Comment by NebbyOtt** [comment]
It seems to be anything mined that can't be smelted gets dropped? Happening to gold blocks, and frankly it just feels a tad strange getting xp from mining stone, is there a way to limit it to only the ores and wood perhaps?

**Comment by Loikas** [comment]
Yeah i'll make it only ores

**Comment by Loikas** [comment]
> It seems to be anything mined that can't be smelted gets dropped? Happening to gold blocks,

Lol about this autosmelt duplicates items, with or without direct you get an item in your inventory, and one is dropped

**Comment by Loikas** [comment]
Fixed in 1.6.3
