### ISSUE TITLE
Enchantments not working 

### ISSUE THREAD

**Issue by killatmining109** [Loikas/ExpandedEnchants#6]
All of the enchantments I have made or tried so far don't work. I can craft and enchant all of the enchantments but they don't do the effect they say they do. I have reloaded the plugin and restarted my server and they still don't work. is there any other plugins I need to make this one work?

**Comment by killatmining109** [comment]
I figured it out. it was conflict with some other plugin I had.

**Comment by Loikas** [comment]
Do you know which plugin caused the issue?

**Comment by killatmining109** [comment]
it was an  older version of Deadly Disasters and a random Magic plugin. I don't really remember the name off the top of my head.
